//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOMEAPP.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryMaster()
        {
            this.InventoryDetails = new HashSet<InventoryDetail>();
        }
    
        public int InventoryMasterId { get; set; }
        public int ProductId { get; set; }
        public double BalanceQuantity { get; set; }
        public int StoreId { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UserIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryDetail> InventoryDetails { get; set; }
        public virtual Setup_Product Setup_Product { get; set; }
        public virtual Setup_Store Setup_Store { get; set; }
    }
}
