//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOMEAPP.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleDetail
    {
        public int RoleDetailId { get; set; }
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public bool isPrimary { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UserIP { get; set; }
    
        public virtual Setup_Role Setup_Role { get; set; }
        public virtual Setup_User Setup_User { get; set; }
    }
}
