//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOMEAPP.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_BusinessAuthentication
    {
        public int BusinessUserId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string NIC { get; set; }
        public int CountryId { get; set; }
        public int CityId { get; set; }
        public int StoreId { get; set; }
        public string Address { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int AuthenticationTypeId { get; set; }
        public string UserIP { get; set; }
    
        public virtual Setup_Store Setup_Store { get; set; }
    }
}
