//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOMEAPP.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Setup_Store()
        {
            this.InventoryMasters = new HashSet<InventoryMaster>();
            this.Setup_BusinessAuthentication = new HashSet<Setup_BusinessAuthentication>();
            this.Setup_User = new HashSet<Setup_User>();
        }
    
        public int StoreId { get; set; }
        public string StoreName { get; set; }
        public string Title { get; set; }
        public string RegisteredNIC { get; set; }
        public string RegisteredNICName { get; set; }
        public System.DateTime OpeningDay { get; set; }
        public int BusinessPlanId { get; set; }
        public string Description { get; set; }
        public string PostalCode { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UserIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryMaster> InventoryMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_BusinessAuthentication> Setup_BusinessAuthentication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_User> Setup_User { get; set; }
    }
}
